twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        asset_front: '%asset_front%'
        asset_back: '%asset_back%'
